name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Server
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Create ,env file
        run: |
          echo "HOST=localhost" >> .env
          echo "USER=root" >> .env
          echo "PASSWORD=${{ secrets.DOCKER_PASSWORD }}" >> .env
          echo "DATABASE=${{ secrets.DOCKER_USERNAME }}" >> .env
          echo "APP_PASSWORD=${{ secrets.DOCKER_APP_PASSWORD }}" >> .env
          echo "SERVEREMAIL=${{ secrets.DOCKER_SERVEREMAIL }}" >> .env

      - name: Build and push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          tags: fufu2345/Software-Engineer-project-server:latest