name: Deploy Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  HOST: localhost
  USER: root
  PASSWORD: ${{ secrets.PASSWORD }}
  DATABASE: ${{ secrets.DATABASE }}
  SERVEREMAIL: ${{ secrets.SERVEREMAIL }}
  APP_PASSWORD: ${{ secrets.APP_PASSWORD }}

jobs:
  deploy:
    name: Deploy Server
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Create .env file
        run: |
          echo "HOST=localhost" >> ./server/.env
          echo "USER=root" >> ./server/.env
          echo "PASSWORD=${{ secrets.PASSWORD }}" >> ./server/.env
          echo "DATABASE=${{ secrets.DATABASE }}" >> ./server/.env
          echo "SERVEREMAIL=${{ secrets.SERVEREMAIL }}" >> ./server/.env
          echo "APP_PASSWORD=${{ secrets.APP_PASSWORD }}" >> ./server/.env

      - name: Build and push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          tags: fufu2345/software-engineer-project-server:latest